/**
 * DockerCon 2017 API
 * This is an exclusive API example for DockerCon 2017 participants.  Tips:   - To fork and work on your own version of this API, select 'Fork API' from the '...' menu   - To share and collaborate on your API, email us clicking below with subject line *\"Special trial for DockerCon participants\"*  Click below to email us: mailto:support@swaggerhub.com 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@swaggerhub.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/EventItem', 'model/SpeakerItem', 'api/AgendaApi', 'api/SpeakersApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/EventItem'), require('./model/SpeakerItem'), require('./api/AgendaApi'), require('./api/SpeakersApi'));
  }
}(function(ApiClient, EventItem, SpeakerItem, AgendaApi, SpeakersApi) {
  'use strict';

  /**
   * This_is_an_exclusive_API_example_for_DockerCon_2017_participants_Tips____To_fork_and_work_on_your_own_version_of_this_API_select_Fork_API_from_the_____menu____To_share_and_collaborate_on_your_API_email_us_clicking_below_with_subject_line_Special_trial_for_DockerCon_participantsClick_below_to_email_usmailtosupportswaggerhub_com.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var DockerCon2017Api = require('index'); // See note below*.
   * var xxxSvc = new DockerCon2017Api.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new DockerCon2017Api.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new DockerCon2017Api.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new DockerCon2017Api.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The EventItem model constructor.
     * @property {module:model/EventItem}
     */
    EventItem: EventItem,
    /**
     * The SpeakerItem model constructor.
     * @property {module:model/SpeakerItem}
     */
    SpeakerItem: SpeakerItem,
    /**
     * The AgendaApi service constructor.
     * @property {module:api/AgendaApi}
     */
    AgendaApi: AgendaApi,
    /**
     * The SpeakersApi service constructor.
     * @property {module:api/SpeakersApi}
     */
    SpeakersApi: SpeakersApi
  };

  return exports;
}));
