/**
 * NOTE: This class is auto generated by the akka-scala (beta) swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * For any issue or feedback, please open a ticket via https://github.com/swagger-api/swagger-codegen/issues/new
 */
package io.swagger.client.api

import io.swagger.client.core._
import io.swagger.client.core.CollectionFormats._
import io.swagger.client.core.ApiKeyLocations._

object NaicsApi {

  /**
   * &lt;p&gt;This endpoint lists all of the NAICS codes that are relevant to the OASIS family of vehicles. It takes no parameters.  &lt;/p&gt;
   * 
   * Expected answers:
   *   code 200 :  (No response was specified)
   */
  def listNaics(): ApiRequest[Unit] =
    ApiRequest[Unit](ApiMethods.GET, "https://dev-virtserver.swaggerhub.com/fbmattos/discovery-market_research/0.1", "/api/naics/", "application/json")
      .withSuccessResponse[Unit](200)
      

}

